"use client";

import { useEffect, useRef, useState } from "react";

import {
  API_URL,
  absoluteAssetUrl,
  localAssetFromFile,
  type AssetItem,
} from "../../lib/assets";
import { authHeaders } from "../../lib/auth";
import { useEditorStore } from "../../lib/editor-store";

interface ApiResponse<T> {
  success: boolean;
  data: T;
  message: string;
}

export function AssetPanel() {
  const fileRef = useRef<HTMLInputElement>(null);
  const [assets, setAssets] = useState<AssetItem[]>([]);
  const [message, setMessage] = useState(
    "Upload an image and place it directly on the canvas.",
  );
  const [uploading, setUploading] = useState(false);
  const insertAsset = useEditorStore((state) => state.insertAsset);
  const selected = useEditorStore((state) =>
    state.selectedNodeId
      ? state.document.nodes[state.selectedNodeId]
      : undefined,
  );

  const loadAssets = async () => {
    try {
      const response = await fetch(`${API_URL}/api/assets`, {
        headers: authHeaders(),
      });
      if (!response.ok) throw new Error("Unable to load assets");
      const result = (await response.json()) as ApiResponse<AssetItem[]>;
      setAssets(result.data);
      setMessage(
        result.data.length
          ? "Click a material to insert it."
          : "No uploaded images yet.",
      );
    } catch {
      setMessage("Start the API to upload and browse materials.");
    }
  };

  useEffect(() => {
    void loadAssets();
  }, []);

  const upload = async (file?: File) => {
    if (!file) return;
    setUploading(true);
    const body = new FormData();
    body.append("file", file);
    try {
      const response = await fetch(`${API_URL}/api/assets/upload`, {
        method: "POST",
        headers: authHeaders(),
        body,
      });
      const result = (await response.json()) as ApiResponse<AssetItem>;
      if (!response.ok) throw new Error(result.message);
      setAssets((current) => [result.data, ...current]);
      insertAsset(result.data);
      setMessage("Image uploaded and added to the canvas.");
    } catch (error) {
      try {
        const localAsset = await localAssetFromFile(file);
        setAssets((current) => [localAsset, ...current]);
        insertAsset(localAsset);
        setMessage(
          "Added locally. Start the API later to save it to the cloud.",
        );
      } catch (localError) {
        setMessage(
          localError instanceof Error
            ? localError.message
            : error instanceof Error
              ? error.message
              : "Upload failed",
        );
      }
    } finally {
      setUploading(false);
      if (fileRef.current) fileRef.current.value = "";
    }
  };

  return (
    <section className="mt-7" aria-label="Assets">
      <div className="mb-3 flex items-center justify-between">
        <h2 className="text-xs font-bold uppercase tracking-widest text-zinc-400">
          Assets
        </h2>
        <button
          className="text-xs font-bold text-violet-600 hover:text-violet-800"
          disabled={uploading}
          onClick={() => fileRef.current?.click()}
        >
          {uploading ? "Adding..." : "Upload image"}
        </button>
        <input
          ref={fileRef}
          className="hidden"
          type="file"
          accept="image/png,image/jpeg,image/webp,image/svg+xml"
          aria-label="Upload image"
          onChange={(event) => void upload(event.target.files?.[0])}
        />
      </div>
      <button
        className="mb-3 flex w-full items-center justify-center rounded-xl border border-dashed border-violet-300 bg-violet-50 px-3 py-3 text-xs font-bold text-violet-700 transition hover:bg-violet-100"
        onClick={() => fileRef.current?.click()}
      >
        Choose from computer
      </button>
      <p className="mb-3 text-xs leading-5 text-zinc-500">{message}</p>
      <div className="grid grid-cols-2 gap-2" data-testid="asset-list">
        {assets.map((asset) => (
          <div
            key={asset.id}
            className="overflow-hidden rounded-lg border border-zinc-200 bg-white"
          >
            <button
              className="block w-full"
              aria-label={`Insert ${asset.filename}`}
              onClick={() => insertAsset(asset)}
            >
              {/* Thumbnail URLs are generated by the trusted asset API. */}
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                className="aspect-square w-full object-cover"
                src={absoluteAssetUrl(asset.thumbnail_url)}
                alt={asset.filename}
              />
            </button>
            {selected?.type === "image" ? (
              <button
                className="w-full border-t border-zinc-200 px-2 py-1 text-[10px] font-bold text-violet-700"
                onClick={() => insertAsset(asset, true)}
              >
                Replace selected
              </button>
            ) : null}
          </div>
        ))}
      </div>
    </section>
  );
}
